spring:
  application:
    name: tracking_order
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/management_order}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:250104}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
    show-sql: true