spring:
  application:
    name: tracking_order
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/db_order}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:250104}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
    show-sql: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm

jwt:
  secret: 80TMFC04qj9DeTh5S9KNEe3v0mAsO+o101pxwSD5oYQ0Dc5RXSJuna1XctOohWFPrDjQJst1wcCAa1pEhomNQ3S3qbSDg17BUvngtM10DfSdO9Fui64+fZwk9Zqmf18vJyZvnEVKsYJ30NIDTNoIFJcZVHHETxZr8AnxUJFmvPHlz9caewpjb+TcjgcOZLU8/SLgP+DP74uMm363DozooJXG7PIiAKAx1ixow2xpdBmT12qgatqxJkswo6AO4GGTK9xDQkCksrCGedHxI/NcjL+MT/EspjqUcIDopVdN/piWNgm71AAJ80DCzrQYYAQrah3jE8YbzPQ4R7ku+LWBTQ==
  issuer: vanchuonglam.com
  expiration: 3600000 # 1 hour in milliseconds
  refreshExpiration: 3600000 # 7 days in milliseconds

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${username}
#    password: ${password}   # App Password, không phải mật khẩu Gmail thật
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true


openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0
